/**
 * Markdown Reporter — Clean markdown test report.
 * @since 4.5.0
 */

import type { SuiteResult } from '../types';
import { calculateCost } from '../cost';

/**
 * Generate a detailed Markdown test report.
 */
export function reportMarkdownDetailed(result: SuiteResult): string {
  const lines: string[] = [];
  const pct = result.total > 0 ? Math.round((result.passed / result.total) * 100) : 0;
  const skipped = result.results.filter(r => r.skipped).length;

  lines.push(`# 🔬 AgentProbe Report: ${result.name}`);
  lines.push('');
  lines.push(`> Generated: ${new Date().toISOString()}`);
  lines.push('');

  // Summary
  lines.push('## Summary');
  lines.push('');
  lines.push(`| Metric | Value |`);
  lines.push(`|--------|-------|`);
  lines.push(`| Total | ${result.total} |`);
  lines.push(`| ✅ Passed | ${result.passed} |`);
  lines.push(`| ❌ Failed | ${result.failed} |`);
  lines.push(`| ⏭️ Skipped | ${skipped} |`);
  lines.push(`| Pass Rate | ${pct}% |`);
  lines.push(`| Duration | ${formatDuration(result.duration_ms)} |`);
  lines.push('');

  // Results table
  lines.push('## Test Results');
  lines.push('');
  lines.push(`| Status | Test | Duration | Tags |`);
  lines.push(`|--------|------|----------|------|`);

  for (const test of result.results) {
    const icon = test.skipped ? '⏭️' : test.passed ? '✅' : '❌';
    const tags = test.tags?.join(', ') ?? '';
    lines.push(`| ${icon} | ${test.name} | ${formatDuration(test.duration_ms)} | ${tags} |`);
  }
  lines.push('');

  // Failures
  const failures = result.results.filter(t => !t.passed && !t.skipped);
  if (failures.length > 0) {
    lines.push('## ❌ Failures');
    lines.push('');
    for (const test of failures) {
      lines.push(`### ${test.name}`);
      lines.push('');
      for (const a of test.assertions.filter(a => !a.passed)) {
        const msg = a.message ?? `expected \`${JSON.stringify(a.expected)}\`, got \`${JSON.stringify(a.actual)}\``;
        lines.push(`- **${a.name}**: ${msg}`);
      }
      if (test.error) {
        lines.push(`- ⚠️ Error: ${test.error}`);
      }
      lines.push('');
    }
  }

  // Cost breakdown
  const costs = result.results
    .filter(r => r.trace)
    .map(r => {
      const cost = calculateCost(r.trace!);
      return { name: r.name, ...cost };
    })
    .filter(c => c.total_cost > 0);

  if (costs.length > 0) {
    lines.push('## 💰 Cost Breakdown');
    lines.push('');
    lines.push(`| Test | Cost |`);
    lines.push(`|------|------|`);
    for (const c of costs) {
      lines.push(`| ${c.name} | $${c.total_cost.toFixed(4)} |`);
    }
    const total = costs.reduce((s, c) => s + c.total_cost, 0);
    lines.push(`| **Total** | **$${total.toFixed(4)}** |`);
    lines.push('');
  }

  lines.push('---');
  lines.push('*Generated by [AgentProbe](https://github.com/neuzhou/agentprobe) v4.5.0*');

  return lines.join('\n');
}

function formatDuration(ms: number): string {
  if (ms >= 60000) return `${(ms / 60000).toFixed(1)}m`;
  if (ms >= 1000) return `${(ms / 1000).toFixed(1)}s`;
  return `${ms}ms`;
}
