/**
 * CI/CD Integration - Generate workflow templates for popular CI providers.
 */

import * as fs from 'fs';
import * as path from 'path';

export type CIProvider = 'github' | 'gitlab' | 'azure-pipelines' | 'circleci' | 'jenkins';

export interface CIOptions {
  provider: CIProvider;
  testPath?: string;
  outputDir?: string;
  output?: string;
  nodeVersion?: string;
}

const GITHUB_WORKFLOW_TEMPLATE = (
  testPath: string,
  nodeVersion: string,
) => `# Generated by AgentProbe - https://github.com/kazhou2024/agentprobe
name: Agent Tests
on: [push, pull_request]

jobs:
  agent-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '${nodeVersion}'

      - name: Install AgentProbe
        run: npm install -g @neuzhou/agentprobe

      - name: Run Agent Tests
        run: agentprobe run ${testPath} -f markdown > results.md
        env:
          OPENAI_API_KEY: \${{ secrets.OPENAI_API_KEY }}

      - name: Upload Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: agent-test-results
          path: results.md

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const results = fs.readFileSync('results.md', 'utf8');
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: '## 🔬 AgentProbe Results\\n\\n' + results
            });
`;

const GITLAB_CI_TEMPLATE = (
  testPath: string,
  nodeVersion: string,
) => `# Generated by AgentProbe - https://github.com/kazhou2024/agentprobe
image: node:${nodeVersion}

stages:
  - test

agent-test:
  stage: test
  script:
    - npm install -g @neuzhou/agentprobe
    - agentprobe run ${testPath} -f junit > results.xml
  artifacts:
    when: always
    reports:
      junit: results.xml
    paths:
      - results.xml
  variables:
    OPENAI_API_KEY: $OPENAI_API_KEY
`;

const AZURE_PIPELINES_TEMPLATE = (
  testPath: string,
  nodeVersion: string,
) => `# Generated by AgentProbe - https://github.com/kazhou2024/agentprobe
trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '${nodeVersion}'

  - script: npm install -g @neuzhou/agentprobe
    displayName: 'Install AgentProbe'

  - script: agentprobe run ${testPath} -f junit > results.xml
    displayName: 'Run Agent Tests'
    env:
      OPENAI_API_KEY: $(OPENAI_API_KEY)

  - task: PublishTestResults@2
    condition: always()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: 'results.xml'
`;

const CIRCLECI_TEMPLATE = (
  testPath: string,
  nodeVersion: string,
) => `# Generated by AgentProbe - https://github.com/kazhou2024/agentprobe
version: 2.1

jobs:
  agent-test:
    docker:
      - image: cimg/node:${nodeVersion}
    steps:
      - checkout
      - run:
          name: Install AgentProbe
          command: npm install -g @neuzhou/agentprobe
      - run:
          name: Run Agent Tests
          command: agentprobe run ${testPath} -f junit > results.xml
      - store_test_results:
          path: results.xml

workflows:
  test:
    jobs:
      - agent-test
`;

const JENKINS_TEMPLATE = (
  testPath: string,
  nodeVersion: string,
) => `// Generated by AgentProbe - https://github.com/kazhou2024/agentprobe
pipeline {
    agent any
    tools {
        nodejs '${nodeVersion}'
    }
    environment {
        OPENAI_API_KEY = credentials('openai-api-key')
    }
    stages {
        stage('Install') {
            steps {
                sh 'npm install -g @neuzhou/agentprobe'
            }
        }
        stage('Test') {
            steps {
                sh 'agentprobe run ${testPath} -f junit > results.xml'
            }
        }
    }
    post {
        always {
            junit 'results.xml'
        }
    }
}
`;

const TEMPLATES: Record<CIProvider, (testPath: string, nodeVersion: string) => string> = {
  'github': GITHUB_WORKFLOW_TEMPLATE,
  'gitlab': GITLAB_CI_TEMPLATE,
  'azure-pipelines': AZURE_PIPELINES_TEMPLATE,
  'circleci': CIRCLECI_TEMPLATE,
  'jenkins': JENKINS_TEMPLATE,
};

const DEFAULT_OUTPUTS: Record<CIProvider, string> = {
  'github': '.github/workflows/agentprobe.yml',
  'gitlab': '.gitlab-ci.yml',
  'azure-pipelines': 'azure-pipelines.yml',
  'circleci': '.circleci/config.yml',
  'jenkins': 'Jenkinsfile',
};

/**
 * Get list of supported CI providers.
 */
export function getSupportedProviders(): CIProvider[] {
  return Object.keys(TEMPLATES) as CIProvider[];
}

/**
 * Generate CI workflow files.
 */
export function generateCI(options: CIOptions): string {
  const testPath = options.testPath || 'tests/';
  const nodeVersion = options.nodeVersion || '20';
  const provider = options.provider;

  const templateFn = TEMPLATES[provider];
  if (!templateFn) {
    throw new Error(`Unsupported CI provider: ${provider}. Supported: ${getSupportedProviders().join(', ')}`);
  }

  const content = templateFn(testPath, nodeVersion);
  const outputPath = options.output || DEFAULT_OUTPUTS[provider];

  const dir = path.dirname(outputPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  fs.writeFileSync(outputPath, content);
  return outputPath;
}

/**
 * Generate CI content without writing to disk.
 */
export function generateCIContent(options: CIOptions): string {
  const testPath = options.testPath || 'tests/';
  const nodeVersion = options.nodeVersion || '20';
  const provider = options.provider;

  const templateFn = TEMPLATES[provider];
  if (!templateFn) {
    throw new Error(`Unsupported CI provider: ${provider}`);
  }

  return templateFn(testPath, nodeVersion);
}
