/**
 * GitHub Actions CI integration — Generate workflow templates for agent testing.
 */

import * as fs from 'fs';
import * as path from 'path';

export interface CIOptions {
  provider: 'github';
  testPath?: string;
  outputDir?: string;
}

const GITHUB_WORKFLOW_TEMPLATE = (testPath: string) => `# Generated by AgentProbe — https://github.com/kazhou2024/agentprobe
name: Agent Tests
on: [push, pull_request]

jobs:
  agent-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install AgentProbe
        run: npm install -g agentprobe

      - name: Run Agent Tests
        run: agentprobe run ${testPath} -f markdown > results.md
        env:
          OPENAI_API_KEY: \${{ secrets.OPENAI_API_KEY }}

      - name: Upload Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: agent-test-results
          path: results.md

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const results = fs.readFileSync('results.md', 'utf8');
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: '## 🔬 AgentProbe Results\\n\\n' + results
            });
`;

/**
 * Generate CI workflow files.
 */
export function generateCI(options: CIOptions): string {
  const testPath = options.testPath || 'tests/';

  if (options.provider === 'github') {
    const dir = options.outputDir || '.github/workflows';
    const filePath = path.join(dir, 'agent-test.yml');

    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }

    const content = GITHUB_WORKFLOW_TEMPLATE(testPath);
    fs.writeFileSync(filePath, content);
    return filePath;
  }

  throw new Error(`Unsupported CI provider: ${options.provider}`);
}
