/**
 * Codegen — Generate YAML tests from recorded traces.
 * Like Playwright codegen: run an agent, auto-generate tests from the trace.
 */

import type { AgentTrace } from './types';
import YAML from 'yaml';

interface GeneratedTest {
  name: string;
  input: string;
  trace: string;
  expect: Record<string, any>;
}

/**
 * Extract key phrases from output text for output_contains assertions.
 */
function extractKeyPhrases(content: string): string[] {
  // Split into sentences, pick meaningful ones (>10 chars, <100 chars)
  const sentences = content
    .split(/[.!?\n]/)
    .map((s) => s.trim())
    .filter((s) => s.length > 10 && s.length < 100);
  // Take first 2 meaningful phrases
  const phrases: string[] = [];
  for (const s of sentences) {
    // Extract a key substring (first noun phrase or significant words)
    const words = s.split(/\s+/).filter((w) => w.length > 3);
    if (words.length >= 2) {
      phrases.push(words.slice(0, 3).join(' '));
    }
    if (phrases.length >= 2) break;
  }
  return phrases;
}

/**
 * Generate test cases from a trace.
 */
export function generateTests(trace: AgentTrace, traceFile: string): GeneratedTest[] {
  const tests: GeneratedTest[] = [];
  const toolCalls = trace.steps.filter((s) => s.type === 'tool_call');
  const outputs = trace.steps.filter((s) => s.type === 'output');
  const totalSteps = trace.steps.length;
  const totalTokens = trace.steps.reduce((sum, s) => {
    const t = s.data.tokens;
    return sum + (t?.input ?? 0) + (t?.output ?? 0);
  }, 0);

  const input = trace.metadata?.input ?? 'TODO: add input';

  // Test 1: Tool usage test (if tools were called)
  if (toolCalls.length > 0) {
    const uniqueTools = [...new Set(toolCalls.map((t) => t.data.tool_name!))];
    const expect: Record<string, any> = {};

    if (uniqueTools.length === 1) {
      expect.tool_called = uniqueTools[0];
    } else {
      expect.tool_called = uniqueTools;
    }

    expect.max_steps = Math.ceil(totalSteps * 1.2);
    if (totalTokens > 0) {
      expect.max_tokens = Math.ceil(totalTokens * 1.2);
    }

    tests.push({
      name: `Agent uses ${uniqueTools.length === 1 ? uniqueTools[0] : 'expected tools'}`,
      input: String(input),
      trace: traceFile,
      expect,
    });
  }

  // Test 2: Output quality test (if there's output)
  if (outputs.length > 0) {
    const allOutput = outputs.map((o) => o.data.content ?? '').join('\n');
    const phrases = extractKeyPhrases(allOutput);
    const expect: Record<string, any> = {};

    if (phrases.length > 0) {
      expect.output_contains = phrases.length === 1 ? phrases[0] : phrases;
    }

    expect.max_steps = Math.ceil(totalSteps * 1.2);
    if (totalTokens > 0) {
      expect.max_tokens = Math.ceil(totalTokens * 1.2);
    }

    tests.push({
      name: 'Agent produces expected output',
      input: String(input),
      trace: traceFile,
      expect,
    });
  }

  // Test 3: Tool sequence test (if multiple tool calls)
  if (toolCalls.length > 1) {
    const sequence = toolCalls.map((t) => t.data.tool_name!);
    tests.push({
      name: 'Agent follows expected tool sequence',
      input: String(input),
      trace: traceFile,
      expect: {
        tool_sequence: sequence,
        max_steps: Math.ceil(totalSteps * 1.2),
      },
    });
  }

  // If no interesting behavior, generate a basic test
  if (tests.length === 0) {
    tests.push({
      name: 'Agent completes without error',
      input: String(input),
      trace: traceFile,
      expect: {
        max_steps: Math.max(Math.ceil(totalSteps * 1.2), 10),
      },
    });
  }

  return tests;
}

/**
 * Format generated tests as YAML with TODO comments.
 */
export function formatGeneratedTests(tests: GeneratedTest[], traceName: string): string {
  const suite = {
    name: `Generated tests from ${traceName}`,
    description: 'Auto-generated by agentprobe codegen. Review and customize assertions.',
    tests: tests,
  };

  let yaml = YAML.stringify(suite, { lineWidth: 120 });

  // Add TODO comments after key assertions
  yaml = yaml.replace(/(output_contains:)/g, '$1 # TODO: customize expected output phrases');
  yaml = yaml.replace(/(tool_called:)/g, '$1 # TODO: verify these are the expected tools');
  yaml = yaml.replace(/(max_steps:)/g, '$1 # TODO: adjust step limit as needed');
  yaml = yaml.replace(/(max_tokens:)/g, '$1 # TODO: adjust token budget as needed');
  yaml = yaml.replace(/(tool_sequence:)/g, '$1 # TODO: verify expected tool order');

  return yaml;
}
