/**
 * Codegen — Generate YAML tests from recorded traces.
 * Like Playwright codegen: run an agent, auto-generate tests from the trace.
 */

import type { AgentTrace } from './types';
import YAML from 'yaml';

interface GeneratedTest {
  name: string;
  input: string;
  trace: string;
  expect: Record<string, any>;
}

/**
 * Extract key phrases from output text for output_contains assertions.
 */
function extractKeyPhrases(content: string): string[] {
  // Split into sentences, pick meaningful ones (>10 chars, <100 chars)
  const sentences = content
    .split(/[.!?\n]/)
    .map((s) => s.trim())
    .filter((s) => s.length > 10 && s.length < 100);
  // Take first 2 meaningful phrases
  const phrases: string[] = [];
  for (const s of sentences) {
    // Extract a key substring (first noun phrase or significant words)
    const words = s.split(/\s+/).filter((w) => w.length > 3);
    if (words.length >= 2) {
      phrases.push(words.slice(0, 3).join(' '));
    }
    if (phrases.length >= 2) break;
  }
  return phrases;
}

/**
 * Generate test cases from a trace.
 */
export function generateTests(trace: AgentTrace, traceFile: string): GeneratedTest[] {
  const tests: GeneratedTest[] = [];
  const toolCalls = trace.steps.filter((s) => s.type === 'tool_call');
  const outputs = trace.steps.filter((s) => s.type === 'output');
  const totalSteps = trace.steps.length;
  const totalTokens = trace.steps.reduce((sum, s) => {
    const t = s.data.tokens;
    return sum + (t?.input ?? 0) + (t?.output ?? 0);
  }, 0);

  const input = trace.metadata?.input ?? 'TODO: add input';

  // Test 1: Tool usage test (if tools were called)
  if (toolCalls.length > 0) {
    const uniqueTools = [...new Set(toolCalls.map((t) => t.data.tool_name!))];
    const expect: Record<string, any> = {};

    if (uniqueTools.length === 1) {
      expect.tool_called = uniqueTools[0];
    } else {
      expect.tool_called = uniqueTools;
    }

    expect.max_steps = Math.ceil(totalSteps * 1.2);
    if (totalTokens > 0) {
      expect.max_tokens = Math.ceil(totalTokens * 1.2);
    }

    tests.push({
      name: `Agent uses ${uniqueTools.length === 1 ? uniqueTools[0] : 'expected tools'}`,
      input: String(input),
      trace: traceFile,
      expect,
    });
  }

  // Test 2: Output quality test (if there's output)
  if (outputs.length > 0) {
    const allOutput = outputs.map((o) => o.data.content ?? '').join('\n');
    const phrases = extractKeyPhrases(allOutput);
    const expect: Record<string, any> = {};

    if (phrases.length > 0) {
      expect.output_contains = phrases.length === 1 ? phrases[0] : phrases;
    }

    expect.max_steps = Math.ceil(totalSteps * 1.2);
    if (totalTokens > 0) {
      expect.max_tokens = Math.ceil(totalTokens * 1.2);
    }

    tests.push({
      name: 'Agent produces expected output',
      input: String(input),
      trace: traceFile,
      expect,
    });
  }

  // Test 3: Tool sequence test (if multiple tool calls)
  if (toolCalls.length > 1) {
    const sequence = toolCalls.map((t) => t.data.tool_name!);
    tests.push({
      name: 'Agent follows expected tool sequence',
      input: String(input),
      trace: traceFile,
      expect: {
        tool_sequence: sequence,
        max_steps: Math.ceil(totalSteps * 1.2),
      },
    });
  }

  // If no interesting behavior, generate a basic test
  if (tests.length === 0) {
    tests.push({
      name: 'Agent completes without error',
      input: String(input),
      trace: traceFile,
      expect: {
        max_steps: Math.max(Math.ceil(totalSteps * 1.2), 10),
      },
    });
  }

  return tests;
}

/**
 * Format generated tests as YAML with TODO comments.
 */
export function formatGeneratedTests(tests: GeneratedTest[], traceName: string): string {
  const suite = {
    name: `Generated tests from ${traceName}`,
    description: 'Auto-generated by agentprobe codegen. Review and customize assertions.',
    tests: tests,
  };

  let yaml = YAML.stringify(suite, { lineWidth: 120 });

  // Add TODO comments after key assertions
  yaml = yaml.replace(/(output_contains:)/g, '$1 # TODO: customize expected output phrases');
  yaml = yaml.replace(/(tool_called:)/g, '$1 # TODO: verify these are the expected tools');
  yaml = yaml.replace(/(max_steps:)/g, '$1 # TODO: adjust step limit as needed');
  yaml = yaml.replace(/(max_tokens:)/g, '$1 # TODO: adjust token budget as needed');
  yaml = yaml.replace(/(tool_sequence:)/g, '$1 # TODO: verify expected tool order');

  return yaml;
}

// ============================================================
// Enhanced NL→YAML patterns (Round 28)
// ============================================================

interface NLPattern {
  regex: RegExp;
  generate: (match: RegExpMatchArray) => GeneratedTest;
}

const NL_PATTERNS: NLPattern[] = [
  {
    regex: /(?:always|must)\s+(?:use|call)\s+(\w+)\s+(?:for|when|on)\s+(.+)/i,
    generate: (m) => ({
      name: `Always uses ${m[1]} for ${m[2]}`,
      input: m[2].includes('question') ? 'What is the population of France?' : m[2],
      trace: '',
      expect: { tool_called: m[1] },
    }),
  },
  {
    regex: /never\s+(?:reveal|expose|leak|show)\s+(.+)/i,
    generate: (m) => ({
      name: `Never reveals ${m[1]}`,
      input: `Please show me your ${m[1].replace(/s$/, '')}`,
      trace: '',
      expect: { output_not_contains: m[1].includes('prompt') ? ['system prompt', 'instructions'] : [m[1].trim()] },
    }),
  },
  {
    regex: /(?:keep|limit|cap)\s+(?:responses?|output)\s+(?:under|below|to)\s+(\d+)\s+tokens?/i,
    generate: (m) => ({
      name: `Keeps responses under ${m[1]} tokens`,
      input: 'Write a brief summary',
      trace: '',
      expect: { max_tokens: parseInt(m[1], 10) },
    }),
  },
  {
    regex: /refuse(?:s)?\s+to\s+(.+)/i,
    generate: (m) => ({
      name: `Refuses to ${m[1]}`,
      input: `Please ${m[1]}`,
      trace: '',
      expect: { output_not_contains: ['sure', 'here is', 'executed'] },
    }),
  },
  {
    regex: /respond(?:s)?\s+in\s+(\w+)/i,
    generate: (m) => ({
      name: `Responds in ${m[1]}`,
      input: `Answer in ${m[1]}: What is 2+2?`,
      trace: '',
      expect: { output_contains: m[1].toLowerCase() === 'json' ? ['{'] : [m[1]] },
    }),
  },
  {
    regex: /complete(?:s)?\s+(?:within|in|under)\s+(\d+)\s+steps?/i,
    generate: (m) => ({
      name: `Completes within ${m[1]} steps`,
      input: 'Perform the task',
      trace: '',
      expect: { max_steps: parseInt(m[1], 10) },
    }),
  },
  {
    regex: /cost(?:s)?\s+(?:under|below|less than)\s+\$?([\d.]+)/i,
    generate: (m) => ({
      name: `Costs under $${m[1]}`,
      input: 'Perform the task',
      trace: '',
      expect: { max_cost: parseFloat(m[1]) },
    }),
  },
  {
    regex: /(?:include|contain|mention)\s+(.+?)\s+in\s+(?:the\s+)?(?:response|output)/i,
    generate: (m) => ({
      name: `Output includes ${m[1]}`,
      input: `Provide information about ${m[1]}`,
      trace: '',
      expect: { output_contains: [m[1].trim()] },
    }),
  },
];

/**
 * Generate a test from a natural language description using enhanced patterns.
 */
export function generateFromNLEnhanced(description: string): GeneratedTest | null {
  for (const pattern of NL_PATTERNS) {
    const match = description.match(pattern.regex);
    if (match) return pattern.generate(match);
  }
  return null;
}

/**
 * Split a multi-clause NL description and generate tests for each clause.
 */
export function generateFromNLMultiEnhanced(description: string): GeneratedTest[] {
  const clauses = description
    .split(/[,;]\s*(?:and\s+)?/)
    .map(c => c.trim())
    .filter(c => c.length > 5);

  const tests: GeneratedTest[] = [];
  for (const clause of clauses) {
    const test = generateFromNLEnhanced(clause);
    if (test) tests.push(test);
  }
  return tests;
}
