/**
 * Init Command - Interactive project setup for AgentProbe.
 * Creates config files, sample tests, and profiles.
 */

import * as fs from 'fs';
import * as path from 'path';

export type AdapterChoice = 'openai' | 'anthropic' | 'ollama' | 'azure' | 'gemini';

export interface InitOptions {
  adapter: AdapterChoice;
  createSampleTests: boolean;
  outputDir: string;
  projectName?: string;
}

export interface InitResult {
  files: string[];
  adapter: AdapterChoice;
  projectName: string;
}

/**
 * Generate the default config YAML for a given adapter.
 */
export function generateConfig(opts: InitOptions): string {
  const lines: string[] = [];
  lines.push(`# AgentProbe Configuration`);
  lines.push(`# Generated by agentprobe init`);
  lines.push(``);
  lines.push(`adapter: ${opts.adapter}`);
  lines.push(`output_dir: reports`);
  lines.push(`test_dir: tests`);
  lines.push(``);

  // Adapter-specific config
  switch (opts.adapter) {
    case 'openai':
      lines.push(`openai:`);
      lines.push(`  model: gpt-4o`);
      lines.push(`  api_key_env: OPENAI_API_KEY`);
      break;
    case 'anthropic':
      lines.push(`anthropic:`);
      lines.push(`  model: claude-sonnet-4-20250514`);
      lines.push(`  api_key_env: ANTHROPIC_API_KEY`);
      break;
    case 'ollama':
      lines.push(`ollama:`);
      lines.push(`  model: llama3`);
      lines.push(`  base_url: http://localhost:11434`);
      break;
    case 'azure':
      lines.push(`azure:`);
      lines.push(`  deployment: gpt-4o`);
      lines.push(`  api_key_env: AZURE_OPENAI_API_KEY`);
      lines.push(`  endpoint_env: AZURE_OPENAI_ENDPOINT`);
      break;
    case 'gemini':
      lines.push(`gemini:`);
      lines.push(`  model: gemini-pro`);
      lines.push(`  api_key_env: GOOGLE_API_KEY`);
      break;
  }

  return lines.join('\n');
}

/**
 * Generate sample test YAML.
 */
export function generateSampleTests(_adapter: AdapterChoice): string {
  return `# Sample AgentProbe Tests
name: sample-tests
description: Getting started with AgentProbe

tests:
  - name: Agent responds to greeting
    input: "Hello, how are you?"
    expect:
      output_contains: hello
      max_steps: 5

  - name: Agent uses tool correctly
    input: "What's the weather in Tokyo?"
    expect:
      tool_called: get_weather
      max_steps: 10
      max_duration_ms: 30000

  - name: Agent stays within budget
    input: "Write a short poem about AI"
    expect:
      max_tokens: 500
      max_cost_usd: 0.05
`;
}

/**
 * Generate profiles YAML.
 */
export function generateProfiles(adapter: AdapterChoice): string {
  return `# AgentProbe Profiles
# Define environment-specific configurations

profiles:
  dev:
    adapter: ${adapter}
    timeout_ms: 60000
    max_retries: 2

  ci:
    adapter: ${adapter}
    timeout_ms: 30000
    max_retries: 1
    parallel: true
    max_concurrency: 4

  production:
    adapter: ${adapter}
    timeout_ms: 120000
    strict: true
`;
}

/**
 * Execute the init command, creating files on disk.
 * Returns list of created files.
 */
export function executeInit(opts: InitOptions): InitResult {
  const baseDir = opts.outputDir;
  const files: string[] = [];
  const projectName = opts.projectName ?? path.basename(process.cwd());

  // Create directories
  const configDir = path.join(baseDir, '.agentprobe');
  const testsDir = path.join(baseDir, 'tests');

  if (!fs.existsSync(configDir)) fs.mkdirSync(configDir, { recursive: true });
  if (!fs.existsSync(testsDir)) fs.mkdirSync(testsDir, { recursive: true });

  // Write config
  const configPath = path.join(configDir, 'config.yml');
  fs.writeFileSync(configPath, generateConfig(opts));
  files.push(configPath);

  // Write profiles
  const profilesPath = path.join(configDir, 'profiles.yml');
  fs.writeFileSync(profilesPath, generateProfiles(opts.adapter));
  files.push(profilesPath);

  // Write sample tests
  if (opts.createSampleTests) {
    const samplePath = path.join(testsDir, 'sample.yaml');
    fs.writeFileSync(samplePath, generateSampleTests(opts.adapter));
    files.push(samplePath);
  }

  return { files, adapter: opts.adapter, projectName };
}

/**
 * Format init result for console display.
 */
export function formatInitResult(result: InitResult): string {
  const lines: string[] = [];
  lines.push(`\n🔬 AgentProbe initialized for "${result.projectName}"!`);
  lines.push(`   Adapter: ${result.adapter}`);
  lines.push(`\n   Created files:`);
  for (const f of result.files) {
    lines.push(`     📄 ${f}`);
  }
  lines.push(`\n   Next steps:`);
  lines.push(`     1. Set your API key environment variable`);
  lines.push(`     2. Edit tests/sample.yaml with your test cases`);
  lines.push(`     3. Run: agentprobe run tests/sample.yaml`);
  return lines.join('\n');
}
